shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3

packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  simple-git-hooks: true
  spawn-sync: false
  unrs-resolver: false
  vue-demi: false
  workerd: false
