# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: voidzero-dev/setup-vp@b5d848f5a62488f3d3d920f8aa6ac318a60c5f07 # v1
        with:
          node-version: '22'
          cache: true

      # - name: 📦 Install browsers
      #   run: vp dlx playwright install

      - name: 🔠 Fix lint errors
        run: vp run lint -- --fix

      - name: 🧪 Update unit test snapshots
        run: vp run -r test:unit -- -u

      # - name: 🏃 Update component test snapshots
      #   run: vp run test:nuxt -- -u

      # - name: 🖥️ Update browser test snapshots
      #   run: vp run test:browser -- --update-snapshots

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # 635ffb0c9798bd160680f18fd73371e355b85f27
