# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1
        with:
          node-version: '22'
          cache: true

      # - name: 📦 Install browsers
      #   run: vp dlx playwright install

      - name: 🔠 Fix lint errors
        run: vp run lint -- --fix

      # - name: 🧪 Update unit test snapshots
      #   run: vp run test:unit -- -u

      # - name: 🏃 Update component test snapshots
      #   run: vp run test:nuxt -- -u

      # - name: 🖥️ Update browser test snapshots
      #   run: vp run test:browser -- --update-snapshots

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # 635ffb0c9798bd160680f18fd73371e355b85f27
