name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: voidzero-dev/setup-vp@2dec1e33f4ab2c6d5bce1b0c4607961bb1a3f7a1 # v1
        with:
          node-version: '22'
          cache: true

      - name: 🔠 Lint project
        run: vp run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: voidzero-dev/setup-vp@2dec1e33f4ab2c6d5bce1b0c4607961bb1a3f7a1 # v1
        with:
          node-version: '22'
          cache: true

      - name: 💪 Type check
        run: vp run test:types

      # - name: 🧪 Unit test
      #   run: vp run test:unit

      # - name: 🏃 Component tests
      #   run: vp run test:nuxt

  # browser:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: mcr.microsoft.com/playwright:v1.49.1-noble

  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: voidzero-dev/setup-vp@v1
  #       with:
  #         node-version: '22'
  #         cache: true

  #     - name: 🖥️ Test project (browser)
  #       run: vp run test:browser
