name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: voidzero-dev/setup-vp@b5d848f5a62488f3d3d920f8aa6ac318a60c5f07 # v1
        with:
          node-version: '22'
          cache: true

      - name: 🔠 Lint project
        run: vp run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: voidzero-dev/setup-vp@b5d848f5a62488f3d3d920f8aa6ac318a60c5f07 # v1
        with:
          node-version: '22'
          cache: true

      - name: 💪 Type check
        run: vp run test:types

      # - name: 🧪 Unit test
      #   run: vp run test:unit

      # - name: 🏃 Component tests
      #   run: vp run test:nuxt

  # browser:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: mcr.microsoft.com/playwright:v1.49.1-noble

  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: voidzero-dev/setup-vp@v1
  #       with:
  #         node-version: '22'
  #         cache: true

  #     - name: 🖥️ Test project (browser)
  #       run: vp run test:browser
